set nocompatible

set autoindent
set list
set listchars=tab:>-,trail:-
set number
set shiftwidth=2
set showmatch
set softtabstop=2
set tabstop=4
set autoread
set backupdir=~/.backup//
set directory=~/.backup//
set expandtab
set guifont=Monaco:h14
set hidden
set hlsearch
set incsearch
set ruler
set showmatch
set showcmd
set showmode
set smartindent
set nowrap

syntax enable
syntax on

" colors torte

" set background=light
set background=dark
colorscheme solarized


filetype on
filetype plugin on
filetype indent on

